-- One-paste setup for a NEW, empty Supabase project: paste into the SQL editor and run once.
-- Generated by concatenating, in order:
--   frontend/drizzle/migrations/0000_portal_schema.sql
--   backend/sql/001_deposit_payments.sql
--   backend/sql/002_project_files_storage.sql
-- Edit those files, not this one.

begin;

-- ===== Portal schema (frontend/drizzle/migrations/0000_portal_schema.sql) =====

create type public.app_role as enum ('admin','client');
create type public.project_status as enum ('discovery','design','development','testing','launched','on_hold');

create table public.profiles (
  id uuid primary key,
  full_name text,
  company text,
  created_at timestamptz not null default now()
);
grant select, insert, update on public.profiles to authenticated;
grant all on public.profiles to service_role;
alter table public.profiles enable row level security;

create table public.user_roles (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null,
  role app_role not null,
  unique(user_id, role)
);
grant select on public.user_roles to authenticated;
grant all on public.user_roles to service_role;
alter table public.user_roles enable row level security;

create or replace function public.has_role(_user_id uuid, _role app_role)
returns boolean language sql stable security definer set search_path = public
as $$ select exists (select 1 from public.user_roles where user_id=_user_id and role=_role) $$;

create policy "own profile read" on public.profiles for select to authenticated using (id = auth.uid() or public.has_role(auth.uid(),'admin'));
create policy "own profile insert" on public.profiles for insert to authenticated with check (id = auth.uid());
create policy "own profile update" on public.profiles for update to authenticated using (id = auth.uid());
create policy "own roles read" on public.user_roles for select to authenticated using (user_id = auth.uid() or public.has_role(auth.uid(),'admin'));

create table public.projects (
  id uuid primary key default gen_random_uuid(),
  client_id uuid not null,
  name text not null,
  description text,
  service text not null default 'Web App',
  status project_status not null default 'discovery',
  progress int not null default 0,
  budget numeric,
  due_date date,
  created_at timestamptz not null default now()
);
grant select, insert, update, delete on public.projects to authenticated;
grant all on public.projects to service_role;
alter table public.projects enable row level security;
create policy "client reads own projects" on public.projects for select to authenticated using (client_id = auth.uid() or public.has_role(auth.uid(),'admin'));
create policy "client creates own request" on public.projects for insert to authenticated with check (client_id = auth.uid() and status = 'discovery' and progress = 0);
create policy "admin updates" on public.projects for update to authenticated using (public.has_role(auth.uid(),'admin'));
create policy "admin deletes" on public.projects for delete to authenticated using (public.has_role(auth.uid(),'admin'));

create table public.project_updates (
  id uuid primary key default gen_random_uuid(),
  project_id uuid not null references public.projects(id) on delete cascade,
  author_id uuid not null,
  message text not null,
  created_at timestamptz not null default now()
);
grant select, insert on public.project_updates to authenticated;
grant all on public.project_updates to service_role;
alter table public.project_updates enable row level security;
create policy "read updates of visible projects" on public.project_updates for select to authenticated
  using (exists (select 1 from public.projects p where p.id = project_id and (p.client_id = auth.uid() or public.has_role(auth.uid(),'admin'))));
create policy "post updates on visible projects" on public.project_updates for insert to authenticated
  with check (author_id = auth.uid() and exists (select 1 from public.projects p where p.id = project_id and (p.client_id = auth.uid() or public.has_role(auth.uid(),'admin'))));

create or replace function public.handle_new_user()
returns trigger language plpgsql security definer set search_path = public as $$
begin
  insert into public.profiles(id, full_name) values (new.id, coalesce(new.raw_user_meta_data->>'full_name', new.raw_user_meta_data->>'name'));
  insert into public.user_roles(user_id, role) values (new.id, 'client');
  if (select count(*) from public.user_roles where role='admin') = 0 then
    insert into public.user_roles(user_id, role) values (new.id, 'admin');
  end if;
  return new;
end $$;
create trigger on_auth_user_created after insert on auth.users for each row execute function public.handle_new_user();

-- ===== Deposit payments (backend/sql/001_deposit_payments.sql) =====

-- Deposit payments. Run once in the Supabase SQL editor.
-- Extends the existing portal schema (public.projects, public.has_role).

-- 1. Price data lives on the project, never in the client -------------------

alter table public.projects
  add column estimate_cents  integer check (estimate_cents > 0),   -- e.g. 1200000 = $12,000.00; null until quoted
  add column deposit_percent integer not null default 25 check (deposit_percent between 1 and 100),
  add column currency        text not null default 'cad' check (currency ~ '^[a-z]{3}$'),
  add column deposit_status  text not null default 'not_started'
             check (deposit_status in ('not_started','pending','paid','needs_review','refunded'));

-- Clients may insert their own project requests and admins may edit projects
-- from the browser, so RLS alone does not protect the new columns. This
-- trigger does: browser sessions can never set deposit_status, and only
-- admins can set the quote. The backend (service_role) is not restricted.
create or replace function public.guard_project_payment_fields()
returns trigger language plpgsql set search_path = public as $$
begin
  if current_user not in ('authenticated', 'anon') then
    return new;
  end if;

  if tg_op = 'INSERT' then
    new.deposit_status := 'not_started';
    if not public.has_role(auth.uid(), 'admin') then
      new.estimate_cents  := null;
      new.deposit_percent := 25;
      new.currency        := 'cad';
    end if;
    return new;
  end if;

  if new.deposit_status is distinct from old.deposit_status then
    raise exception 'deposit_status is managed by the payment backend';
  end if;
  if not public.has_role(auth.uid(), 'admin') and (
       new.estimate_cents  is distinct from old.estimate_cents
    or new.deposit_percent is distinct from old.deposit_percent
    or new.currency        is distinct from old.currency) then
    raise exception 'only admins can change the estimate';
  end if;
  return new;
end $$;

create trigger guard_project_payment_fields
  before insert or update on public.projects
  for each row execute function public.guard_project_payment_fields();

-- 2. One row per checkout attempt ------------------------------------------

create table public.payments (
  id                    uuid primary key default gen_random_uuid(),
  project_id            uuid not null references public.projects(id),
  user_id               uuid not null references auth.users(id),
  purpose               text not null default 'deposit',
  amount_cents          integer not null check (amount_cents > 0),
  currency              text not null,
  stripe_session_id     text unique,
  stripe_payment_intent text,
  status                text not null default 'pending'
                        check (status in ('pending','paid','expired','failed','needs_review','refunded')),
  created_at            timestamptz not null default now()
);

-- At most one open deposit attempt per project: a concurrent double-click
-- cannot create two Checkout Sessions.
create unique index payments_one_pending_deposit
  on public.payments (project_id) where purpose = 'deposit' and status = 'pending';

create index payments_project_id_idx on public.payments (project_id);

-- 3. Webhook de-duplication -------------------------------------------------

create table public.stripe_events (
  id          text primary key,         -- Stripe event ID (evt_...)
  type        text not null,
  received_at timestamptz not null default now()
);

-- 4. Access -----------------------------------------------------------------

alter table public.payments      enable row level security;
alter table public.stripe_events enable row level security;

-- Clients may READ their own payments. No insert/update/delete policies or
-- grants, so only the backend (secret key) can change payment state.
revoke all on public.payments, public.stripe_events from anon, authenticated;
grant select on public.payments to authenticated;
grant all on public.payments, public.stripe_events to service_role;

create policy "owner or admin reads payments"
  on public.payments for select to authenticated
  using (user_id = auth.uid() or public.has_role(auth.uid(), 'admin'));

-- stripe_events: no policies = no client access at all

-- ===== Project files storage (backend/sql/002_project_files_storage.sql) =====

-- Project files (Supabase Storage). Run once in the Supabase SQL editor,
-- after the portal schema.
-- Objects live at <project_id>/<file name> in a private bucket, so access
-- follows the same rule as the project itself: its client, or an admin.

insert into storage.buckets (id, name, public, file_size_limit)
values ('project-files', 'project-files', false, 26214400)   -- 25 MB per file
on conflict (id) do nothing;

create or replace function public.can_access_project_files(_object_name text)
returns boolean language sql stable security definer set search_path = public
as $$
  select exists (
    select 1 from public.projects p
    where p.id::text = (storage.foldername(_object_name))[1]
      and (p.client_id = auth.uid() or public.has_role(auth.uid(), 'admin'))
  )
$$;

create policy "read files of visible projects"
  on storage.objects for select to authenticated
  using (bucket_id = 'project-files' and public.can_access_project_files(name));

create policy "upload files to visible projects"
  on storage.objects for insert to authenticated
  with check (bucket_id = 'project-files' and public.can_access_project_files(name));

create policy "uploader or admin deletes files"
  on storage.objects for delete to authenticated
  using (
    bucket_id = 'project-files'
    and (owner_id = auth.uid()::text or public.has_role(auth.uid(), 'admin'))
  );

commit;
